export const GET_PRODUCTS = 'getProducts'
export const SET_PRODUCTS = 'setProducts'
export const POST_PRODUCT = 'postProduct'
export const PUT_PRODUCT = 'putProduct'
export const DELETE_PRODUCT = 'deleteProduct'
export const EDIT_PRODUCT = 'editProduct'
export const SET_EDIT_MODE = 'setEditMode'